version: "3"

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    env_file:
      - .env
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - network
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
        required: true
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - network
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - network
    restart: always
    healthcheck:
      test: ["CMD", "/etc/healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 1m
      timeout: 5s
      retries: 10
      start_period: 2s

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: ~/data/mariadb
      o: bind
      type: none

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: ~/data/wordpress
      o: bind
      type: none

networks:
  network:
    name: network
    driver: bridge

